### ISSUE TITLE
gson JsonParseException / JsonSyntaxException

### ISSUE THREAD

**Issue by dmeggyesy** [hjsong6230/COMP90015#1]
Classes look good, however, might be a bit redundant.

Apparently JsonParseException and JsonSyntaxException don't get thrown when we'd like them to.
See:
http://stackoverflow.com/questions/14242236/let-gson-throw-exceptions-on-wrong-types
Specifically, gson will try and "make" variables fit.  Anything that is in the Json object, but not in the POJO object is simply *ignored*.  Anything that is in the POJO but not the Json object, is set to null in the POJO.

Basically this means we're going to have to manually error check our messages.  (and we probably could've just kept things how they were >.<)

The inherited class structure we have now still may be useful for _sending_ Json objects through gson.  I imagine toJson probably spits out empty fields if the POJO has said variables, which would not be to spec.  So at least we're getting neatly formatted json objects.  (which we were anyway by addparameter, but anyway!)
(Confirmed, empty variables spit out NULL json fields:  http://stackoverflow.com/questions/21120999/representing-null-in-json)
This means we can't just have one big message class with all the variables though.

So, we can either do error checking at the switch case, checking to see if any of the valid parameters are NULL.  This unfortunately won't catch any "extra" parameters sent along.

Or at MessageObject constructor level, which _also_ won't filter out "extra" parameters.

JsonObject.entrySet().size() will however tell us how many fields there are in the json object.  
Which was of course easier to get when we _weren't_ using gson.toJson and gson.FromJson.  

Anyway, long story short, it's a little disappointing that we've spent all day getting the gson thing working, and it turns out we are arguably only slightly better off for it.  

I've implemented the error checking (at the switch case) for all cases that currently have functionality, as well as tested it (via telnet).

I'll go through the other commands tomorrow afternoon and add in the error checking for them also.

**Comment by hjsong6230** [comment]
Took me ages to figure out why we can't use basic Message object but then realised we might have to consider when user send JSON string that happens to match the POJO definition along with some random jargons. I'm on the same page now haha.

Alright, whenever you want, merge the branch into the source branch then I can work off of that. If not, I might keep working on the branch I was on.

This thing is due on the end of week 8 and we are on week 6 if I am correct?

**Comment by dmeggyesy** [comment]
A basic POJO "catchall" message object will work, it just won't clearly define the protocol, in regards to invalid messages.

Consider,
{"command":"AUTHENTICATE"}
json will parse that into our MessageAuthenticate object happily and not throw any exception.
However,
MessageAuthenticate.getCommand() will return AUTHENTICATE (no problem)
MessageAuthenticate.getSecret() will return NULL.  (big problem).

Consider a catchall "Message" object:
Message {
String command;
string secret;
int load;
int port;
string host;
}
Now say we want to use gson to write out an authenticate message, using that object.
it would output:
{"command":"AUTHENTICATE","secret":"inputtedsecret","load":0,"port":0,"host":null}

Which again, is not correctly implementing the protocol specification.

I'll merge what I've currently got going into master in a few mins, it has all the server side "error checking" done, so that isn't an issue anymore, and so on.

I believe end of week 8 is due date, yes.

**Comment by hjsong6230** [comment]
If that was the only problem, couldn't we done something along this line?
Message message = New Message(""); //Empty string as command
try{
  message = gson.toObject(jsonMessage);
}catch(Exception e){
  Invalid Message
}

switch(message.command){
  case "":
    Invalid Message
    return true
  case ANYTHING ELSE:
    Create POJO of matching type
    To stuff
}

But thing is that user can send mash of two command, which should be invalid but if it just goes my value of command, it might let it slip. So we need to check the number of argument coming in at least. (We don't need to check the keys of the object since if they don't match, POJO will have dirty values.)

Or am I missing something here? (Apart from the annoying fact that we need to make a Message object just to do the error checking)

**Comment by dmeggyesy** [comment]
you mean, gson.fromJson(jsonMessage, Message.class) I presume.
It's not going to throw any exceptions though, gson tries to "intelligently" "fix" the json objects/variables, and so on.  So again, that will still "catch" everything that WE want, but if the message has a garbage field we DON'T want, it'll happily go ahead and ignore it - which isn't what the protocol says.  If the message is WRONG, in that it has the WRONG fields, it's trash the message, send back an invalid_message, and close the connection.

{"command":"AUTHENTICATE","banana":"banana"} would still be parsed by what you have there I think.  It has a correct command field, but garbage second field.  (which would also fool a field count check).

Have a look at the master branch now, it's all in there anyway and it works well enough.  It's tedious as error checking usually is, but it should *not* allow any sort of invalid Json messages through.  It should also not allow any invalid Json messages to (currently) be sent, while using the correct objects (the ones you added lastnight).

If you want to test that it's working, you can fire up a server and telnet to it, and send some garbage Json messages and see what it does.  It should reply properly to anything valid (that is implemented) and reply with INVALID_MESSAGE to anything not valid.

The ACTIVITY_BROADCAST passing around seems to be working properly also, I checked it with telnet and 4 servers running in a tree, all servers get the message properly, and presumably it's parsing in the JsonObject properly.

**Comment by hjsong6230** [comment]
...I can't believe  didn't condider the case where message might come with a command that doesn't match the content... yep, you are right. Sorry about that
